- hosts: masters
  become: yes
  tasks:
    - name: Reset kubeadm
      shell: kubeadm reset --force

    - name: Remove existing Kubernetes files and directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes/manifests/kube-apiserver.yaml
        - /etc/kubernetes/manifests/kube-controller-manager.yaml
        - /etc/kubernetes/manifests/kube-scheduler.yaml
        - /etc/kubernetes/manifests/etcd.yaml
        - /etc/kubernetes/manifests/kube-proxy.yaml
        - /var/lib/etcd
      ignore_errors: true

    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16

    - name: Create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: "~/.kube"
        state: directory
        mode: 0755

    - name: Check if admin.conf file exists
      stat:
        path: /etc/kubernetes/admin.conf
      register: k8s_conf

    - name: Wait until SSL certificates are generated
      wait_for:
        path: "/etc/kubernetes/admin.conf"
      when: k8s_conf.stat.exists

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "~/.kube/config"
        remote_src: yes
        owner: ubuntu
      when: k8s_conf.stat.exists

    - name: Install calico Pod network
      shell:  kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        chdir: $HOME