apiVersion: v1
kind: Service
metadata:
  name: coffee-project-service
spec:
  selector:
    app: coffee
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31000
  type: NodePort
