- hosts: masters
  become: yes
  gather_facts: false
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Copy join command to local file
      become: yes
      local_action:
        module: copy
        content: "{{ join_command_raw.stdout_lines[0] }}"
        dest: "/tmp/kubernetes_join_command"
        mode: '0777'

- hosts: workers
  become: yes
  tasks:
    - name: Copy join command from Ansible host to the worker nodes
      become: yes
      copy:
        src: "/tmp/kubernetes_join_command"
        dest: "/tmp/kubernetes_join_command"
        mode: '0777'

    - name: Remove existing Kubernetes files on worker nodes
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/kubernetes/bootstrap-kubelet.conf
        - /etc/kubernetes/pki/ca.crt

    - name: Join the Worker nodes to the cluster
      become: yes
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not
