---
- name: Deploy Prometheus and Grafana
  hosts: monitoring_server
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - software-properties-common
          - unzip
      when: ansible_os_family == 'Debian'

    - name: Add Grafana APT repository key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
      when: ansible_os_family == 'Debian'

    - name: Add Grafana APT repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Prometheus
      ansible.builtin.apt:
        name: prometheus
      when: ansible_os_family == 'Debian'

    - name: Install Grafana
      nsible.builtin.apt:
        name: grafana
      when: ansible_os_family == 'Debian'

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Open port 9090 for Prometheus
      ufw:
        rule: allow
        port: 9090

    - name: Open port 3000 for Grafana
      ufw:
        rule: allow
        port: 3000

- name: Configure Prometheus Targets
  hosts: monitoring_server
  become: true

  tasks:
    - name: Update Prometheus configuration
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
      notify: Reload Prometheus

  handlers:
    - name: Reload Prometheus
      systemd:
        name: prometheus
        state: reloaded

- name: Configure Prometheus Data Source in Grafana
  hosts: localhost
  tasks:
    - name: Install Grafana Data Source
      grafana_datasource:
        name: Prometheus
        access: proxy
        url: http://143.198.68.194:3000/
        is_default: true
        ds_type: prometheus
        ds_url: http://143.198.68.194:9090
      register: prometheus_datasource