{
 "title": "Prometheus2.0",
 "description": "Dashboard providing insight to Prometheus monitoring system status and it's runtime info.",
 "tags": [
  "prometheus",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Observed instance",
    "query": "label_values(prometheus_build_info, instance)"
   },
   { "name": "custom_label_name", "label": "Custom label name", "query": "${VAR_CUSTOM_LABEL_NAME}" },
   {
    "name": "custom_label_value",
    "label": "Custom label value",
    "query": "label_values(prometheus_build_info, $custom_label_name)"
   },
   {
    "name": "aggregation_interval",
    "label": "Aggregation intarval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": "query_result({__name__=~\"prometheus_.*_seconds\"})"
   },
   {
    "name": "long_term_interval",
    "query": "10m,30m,1h,6h,12h,1d,3d,1w,4w,12w,1y"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "content": "# 🧦 Welcome!\nIn case you encounter any issues or have a feature request, please refer to the GitHub reposritory [https://fusakla.github.io/Prometheus2-grafana-dashboard](https://fusakla.github.io/Prometheus2-grafana-dashboard)\n\n\n### Few advices:\n - The constant type variable `custom_label_name` allows you to identify the Prometheus instance by additional label. By default it's identified by `instance` and `job` (default value of the custom label).\n - Queries using `increase` or `rate` use the interval variable `Aggregation interval` as a range vector selector. Title of graph should always show the interval value.\n - All panels which describes latency mostly shows quantile. This is controlled by the variable `Quantile` so make use of it.\n - Some panels uses overrided time interval to longer value, this can be controlled by the `Long term interval` variable.\n - Beware that some collapsed rows could be query expensive on the datasource (depends on complexity of observed Prometheus config or number of those instances). Better make sure to pick only one particular\n   instance before expanding those rows.\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "content": "<img src=\"https://cdn.worldvectorlogo.com/logos/prometheus.svg\"/ height=\"140px\">"
  },
  {
   "title": "Build, uptime and runtime instance info",
   "type": "table",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 6 },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)"
    },
    {
     "expr": "max(prometheus_build_info{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name, branch, goversion, version, revision)"
    },
    {
     "expr": "max(prometheus_config_last_reload_successful{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)"
    },
    {
     "expr": "max(sum(prometheus_rule_group_rules{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name) or prometheus_build_info{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}*0) by (instance,$custom_label_name)"
    },
    {
     "expr": "max(sum(prometheus_sd_discovered_targets{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", name=\"scrape\"}) by (instance,$custom_label_name) or prometheus_build_info{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}*0) by (instance,$custom_label_name)"
    },
    {
     "expr": "max(prometheus_tsdb_head_series{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)"
    },
    {
     "expr": "time() - max(prometheus_tsdb_lowest_timestamp_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)"
    },
    {
     "expr": "min(prometheus_tsdb_storage_blocks_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)"
    }
   ]
  },
  { "title": "Main info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Number of time series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(prometheus_tsdb_head_series{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
     "legendFormat": "{{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "$quantile quantile of interval length between scrapes per job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\",quantile=\"$quantile\"}",
     "legendFormat": "{{instance}}/{{$custom_label_name}} job {{job}} should be {{interval}}"
    }
   ]
  },
  {
   "title": "Prometheus errors in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  increase(\n    label_replace({__name__=~\"(:?prometheus|net_conntrack)_.*(:?fail|duplicate|out_of|error|not_found|corrupt|dropped|missed|exceeded).*_total\", instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}, \"metric_name\", \"$1\", \"__name__\", \"(.*)\")[$aggregation_interval:20s]\n  )\n) by (instance,$custom_label_name,metric_name,alertmanager,name,mechanism,queue) > 0"
    }
   ]
  },
  { "title": "Requests & queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "HTTP request count by handler in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_http_requests_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name, handler) ",
     "legendFormat": " {{ handler }} handler on {{ instance }}/{{ $custom_label_name }}"
    }
   ]
  },
  {
   "title": "$quantile quantile of HTTP request duration per handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(increase(prometheus_http_request_duration_seconds_bucket{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (le,instance, handler))",
     "legendFormat": "{{ handler }} handler on {{instance}}/{{$custom_label_name}} "
    }
   ]
  },
  {
   "title": "$quantile of request size by handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(increase(prometheus_http_response_size_bytes_bucket{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (le,instance, handler)) > 0",
     "legendFormat": "{{ handler }} handler on {{ instance }}/{{ $custom_label_name }}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name)",
     "legendFormat": "CPU usage of {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
     "legendFormat": "Resident memory of {{instance}}/{{$custom_label_name}}"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
     "legendFormat": "Total allocated bytes of {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "Allocations per second in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])",
     "legendFormat": "Allocated Bytes of {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  { "title": "TSDB stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Oldest data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - min(prometheus_tsdb_lowest_timestamp_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
     "legendFormat": "Oldest data for {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "Size of the storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(prometheus_tsdb_storage_blocks_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
     "legendFormat": "Storage size of {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "Query engine & API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of concurent queries and it's limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_engine_queries{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "{{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "sum(prometheus_engine_queries_concurrent_max{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "{{instance}}/{{$custom_label_name}} Limit"
      }
     ]
    },
    {
     "title": "$quantile quantile of query engine evaluation duration per slice",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "prometheus_engine_query_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", quantile=\"$quantile\"}",
       "legendFormat": "{{slice}} slice on {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Number of queries on remote read API",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_api_remote_read_queries{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "{{instance}}/{{$custom_label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rule evaluation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage rule group evaluation duration from the rule group evaluation interval (top 20)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(20,\nmax(prometheus_rule_group_last_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (rule_group, instance) /\nmin(prometheus_rule_group_interval_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (rule_group, instance)\n)\n",
       "legendFormat": "Percentage of {{rule_group}} group evaluation interval on {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "$quantile quantile of rule evaulation duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_rule_evaluation_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", quantile=\"$quantile\"}) by (instance,$custom_label_name, quantile)",
       "legendFormat": "evaluation duration of {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Number of rules per group (top 20 groups)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(topk(20,prometheus_rule_group_rules{instance=~\"$instance\", $custom_label_name=~\"$custom_label_value\"})) by (instance,$custom_label_name, rule_group)",
       "legendFormat": "number of rules in {{rule_group}} rule group on {{instance}}/{{$custom_label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notification queue size and capacity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_notifications_queue_length{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"})by (instance,$custom_label_name)",
       "legendFormat": "Queue size of {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "sum(prometheus_notifications_queue_capacity{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"})by (instance,$custom_label_name)",
       "legendFormat": "Queue capacity of {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Number of sent notifictions per alertmanager in $aggregation_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(prometheus_notifications_sent_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name, alertmanager)",
       "legendFormat": "Sent notifications to {{alertmanager}} alertmanager from {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "$quantile of notification latency per alertmanager",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(prometheus_notifications_latency_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", quantile=\"$quantile\"}) by (instance,$custom_label_name, alertmanager)",
       "legendFormat": "Latency of notifications sent to {{alertmanager}} from  {{instance}}/{{$custom_label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of discovered targets per Type and config",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_sd_discovered_targets{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", name=\"scrape\"}) by (instance,$custom_label_name,config,name)",
       "legendFormat": "Number of {{name}} type targets from config {{config}} on {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Service discovery  sync count by mechanism in $aggregation_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(prometheus_sd_refresh_duration_seconds_count{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name,mechanism)",
       "legendFormat": "Number of sync for {{mechanism}} SD mechanism on {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "sum(increase(prometheus_sd_consul_rpc_duration_seconds_count{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name)",
       "legendFormat": "Number of sync for consul SD mechanism on {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "sum(increase(prometheus_sd_kubernetes_http_request_duration_seconds_count{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name)",
       "legendFormat": "Number of sync for kubernetes SD mechanism on {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "$quantile quantile of refresh duration per SD mechanism",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "prometheus_sd_refresh_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", quantile=\"$quantile\"}",
       "legendFormat": "Duration of sync for {{mechanism}} SD mechanism on {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "consul_rpc_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", quantile=\"$quantile\"}",
       "legendFormat": "Number of sync for consul SD mechanism on {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "prometheus_sd_file_scan_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", quantile=\"$quantile\"}",
       "legendFormat": "Duration of sync for file_scan SD mechanism on {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "prometheus_sd_kubernetes_http_request_duration_seconds_sum{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"} / prometheus_sd_kubernetes_http_request_duration_seconds_count{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}",
       "legendFormat": "AVG Duration of sync for k8s SD mechanism on {{instance}}/{{$custom_label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compaction and retention",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "$quantile quantile of compaction duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum(rate(prometheus_tsdb_compaction_duration_seconds_bucket{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name, le))",
       "legendFormat": "Compaction duration on {{ instance }}/{{ $custom_label_name }}"
      }
     ]
    },
    {
     "title": "Number of vertical/horizontal compactions in last $aggregation_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_compactions_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name) > 0",
       "legendFormat": "Count of horizontal compactions on {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_vertical_compactions_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name) > 0",
       "legendFormat": "Count of vertical compactions  on {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Number of time/size retention cutoffs in $aggregation_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_size_retentions_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name) > 0",
       "legendFormat": "Number of size retention cutoffs on  {{ instance }}/{{ $custom_label_name }}"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_time_retentions_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name) > 0",
       "legendFormat": "Number of time retention cutoffs on {{ instance }}/{{ $custom_label_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Head block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Head chunks count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_tsdb_head_chunks{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "Head block chunk count on  {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Samples Appended per second in $aggregation_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name)",
       "legendFormat": "Appended samples/s on {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Time series total count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}",
       "legendFormat": "Time series count of  {{instance}}/{{$custom_label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "$quantile quantile of WAL fsync duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_tsdb_wal_fsync_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\",quantile=\"$quantile\"}) by (instance,$custom_label_name)",
       "legendFormat": "Duration of WAL fsync on {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Number of completed pages in $aggregation_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_wal_completed_pages_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name)",
       "legendFormat": "Completed WAL pages count of {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Average duration of WAL truncation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_tsdb_wal_truncate_duration_seconds_sum{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"} /\nprometheus_tsdb_wal_truncate_duration_seconds_count{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "Duration of WAL truncation on {{instance}}/{{$custom_label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of queries to remote storage per client",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_remote_storage_remote_read_queries{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name, client)",
       "legendFormat": "Number of queries to {{client}} client from {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Number of samles successfuly sent to remote storage per queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(prometheus_remote_storage_succeeded_samples_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name, queue)",
       "legendFormat": "Number of samples sent to {{queue}}  from {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "$quantile quantile of batch send call duration to remote storage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantile,sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name, queue, le))",
       "legendFormat": "Duration of batch send to {{queue}}  from {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Number of used shards for concurent sending of data to remote storage and it's capacity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_remote_storage_shards{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name, queue)",
       "legendFormat": "Number of shards used for {{queue}} on {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "min(prometheus_remote_storage_shard_capacity{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name, queue)",
       "legendFormat": "Limit of shards that can be used for {{queue}} on {{instance}}/{{$custom_label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of gorutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(go_goroutines{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "Gorutines count of {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Duration of Go garbage collection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(go_gc_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "GC duration on {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Go system memory allocations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(go_memstats_mspan_sys_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "mspan {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "max(go_memstats_mcache_sys_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "mcache {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "max(go_memstats_buck_hash_sys_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "buck_hash {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "max(go_memstats_gc_sys_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "gc {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "max(go_memstats_other_sys_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "other {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "max(go_memstats_stack_sys_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "stack {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "max(go_memstats_heap_sys_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
       "legendFormat": "heap {{instance}}/{{$custom_label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accepted/closed inbound connections per listener",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(net_conntrack_listener_conn_accepted_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name, listener_name) > 0",
       "legendFormat": "{{listener_name}} accepted connections on {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "sum(increase(net_conntrack_listener_conn_closed_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name, listener_name) > 0",
       "legendFormat": "{{listener_name}} closed connections on {{instance}}/{{$custom_label_name}}"
      }
     ]
    },
    {
     "title": "Established/closed outbound connections per dialer ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(net_conntrack_dialer_conn_established_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name, dialer_name) > 0",
       "legendFormat": "{{dialer_name}} established connections on {{instance}}/{{$custom_label_name}}"
      },
      {
       "expr": "sum(increase(net_conntrack_dialer_conn_closed_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name, dialer_name) > 0",
       "legendFormat": "{{dialer_name}} closed connections on {{instance}}/{{$custom_label_name}}"
      }
     ]
    }
   ]
  }
 ]
}