name: ansible linter

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Ansible Lint
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
