name: Ansible Lint

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Ansible Lint
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ansible-lint
        run: |
          docker pull pipelinecomponents/ansible-lint
          docker run --rm -v ${{ github.workspace }}:/playbook pipelinecomponents/ansible-lint ansible-playbook /playbook/ansible-linter.yaml
