name: Ansible Lint

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Ansible Lint
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ansible-lint
        working-directory: .
        run: |
          docker pull pipelinecomponents/ansible-lint
          PLAYBOOK_PATH=$(find . -type f -name "*.yaml" -o -name "*.yml" | head -n 1)
          
          if [ -z "$PLAYBOOK_PATH" ]; then
            echo "No Ansible playbook found."
          else
            docker run --rm -v ${{ github.workspace }}:/playbook pipelinecomponents/ansible-lint ansible-playbook $PLAYBOOK_PATH
          fi