name: ansible linter

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Ansible Lint
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
