name: Ansible Lint

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Ansible Lint
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ansible-lint
        working-directory: ${{ github.workspace }}
        run: |
          docker pull pipelinecomponents/ansible-lint
          PLAYBOOK_PATH=$(find . -type f -name "*.yaml" -o -name "*.yml" | head -n 1)
          
          if [ -z "$PLAYBOOK_PATH" ]; then
            echo "No Ansible playbook found."
          else
            PLAYBOOK_PATH_RELATIVE=$(realpath --relative-to=${{ github.workspace }} $PLAYBOOK_PATH)
            echo "Running ansible-lint on playbook: /playbook/${PLAYBOOK_PATH_RELATIVE}"
            docker run --rm -v ${{ github.workspace }}:/playbook pipelinecomponents/ansible-lint ansible-lint /playbook/${PLAYBOOK_PATH_RELATIVE}
          fi