name: canary-release

on:
  pull_request:
    branches:
      - 'release**'
    types:
      - closed
  # TODO: DELETE LATER- JUST FOR TESTING PURPOSES
  push:
    branches:
      - feature-*

jobs:
  build:
    name: Build Release Docker Image
    # if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Give sudo permissions
        run: sudo usermod -a -G docker root
      
      - name: Build Docker image
        working-directory: canary
        run: docker build -t setup-k8s .
        
      - name: Run Docker container
        run: |
          docker run -v /root/.ssh:/root/.ssh/ setup-k8s ansible-playbook -i inventory/mycluster/hosts.yaml --become --become-user=root --user=ubuntu --private-key /root/.ssh/id_rsa cluster.yml
  
  canary-deploy:
    name: Begin Canary Deployment
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
