name: Common Vulnerability Job
on:
  pull_request:
    branches:
      - 'dev'
      - 'release**'

jobs:
  vulnerability:
    name: Check for vulnerabilities
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
