# common-job.yml
name: Common Vulnerability Job
on:
  workflow_run:
    workflows: ["workflow1", "workflow2"]
    types:
      - completed
  # custom:
  #   common-vulnerability-job-trigger: {}

jobs:
  vulnerability:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2