name: Common Vulnerability Job
on:
  pull_request:
    branches:
      - 'dev'
      - 'release**'

jobs:
  vulnerability:
    name: Check for vulnerabilities
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: coffee-project
        run: npm install

      - name: Run npm audit
        working-directory: coffee-project
        run: npm audit --audit-level=high