name: deploy
on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  build:
    name: Build Release Docker Image and push to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - run: |
          docker build ./coffee-project -t lgjenqui/coffee-project:release
          docker push lgjenqui/coffee-project:release

  release-deploy:
    name: Begin Deployment
    needs: build
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v2.0

      - name: Setup K8s context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v4
        with:
          secret-name: 'coffee-project-pat'
          container-registry-url: 'docker.io'
          container-registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          container-registry-password: ${{ secrets.DOCKERHUB_PAT }}
        id: create-secret

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          action: promote
          strategy: canary
          force: true
          manifests: |
              canary/coffee.yaml
              canary/service.yaml
          images: |
              docker.io/lgjenqui/coffee-project:release

  reject-canary:
    name: Reject Canary Deployment
    if: github.event.pull_request.merged == false
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v2.0

      - name: Setup K8s context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v4
        with:
          secret-name: 'coffee-project-pat'
          container-registry-url: 'docker.io'
          container-registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          container-registry-password: ${{ secrets.DOCKERHUB_PAT }}
        id: create-secret

      - name: Reject canary build
        uses: Azure/k8s-deploy@v4
        with:
          action: reject
          strategy: canary
          force: true
          manifests: |
              canary/coffee.yaml
              canary/service.yaml
          images: |
              docker.io/lgjenqui/coffee-project:canary
