name: deploy
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target Branch for PR'
        required: true
        default: 'main'

jobs:
  deploy:
    name: Deploy latest version
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
