name: dev-merge-project
on:
  pull_request
jobs:
  build:
    name: Linting
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  test:
    name: Unit Testing
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  coverage:
    name: Coverage Check
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  vulnerability:
    name: Vulnerability Check
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
