name: ESLint

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - feature-*
defaults:
      run:
        working-directory: coffee-project
jobs:
  lint:
    name: ESLint Check
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Debug ESLint Command
      run: npm run lint --dir test --dir public

    - name: Run ESLint
      run: npm run lint
