name: ESLint

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - feature-*

jobs:
  lint:
    name: ESLint Check
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      working-directory: coffee-project
      run: npm install

    - name: Set ECMAScript Version
      working-directory: coffee-project
      run: |
        echo '{"parserOptions": {"ecmaVersion": 12}}' > .eslintrc.json

    - name: Run ESLint
      working-directory: coffee-project
      run: npm run lint