name: Build, Run, and Test Docker Image and ensure the app is running

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - feature-*

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Port Availability
      run: |
        PORT=3000
        if [ "$(lsof -ti :$PORT)" ]; then
          echo "Port $PORT is already in use."
          CONFLICTING_PROCESS_PID=$(lsof -ti :$PORT)
          echo "Stopping the conflicting process with PID $CONFLICTING_PROCESS_PID"
          kill -9 $CONFLICTING_PROCESS_PID
          sleep 5  # Wait for the process to be terminated
        else
          echo "Port $PORT is available."
        fi

    - name: Build Docker Image
      working-directory: coffee-project
      run: docker build -t coffee-app .

    - name: Run Docker Container
      run: docker run -d -p 3000:3000 coffee-app

    - name: Display Running Containers
      run: docker ps

    - name: Wait for Application to Start
      run: sleep 10

    - name: Test Website Availability
      run: |
        if [ "$(curl -s -o /dev/null -w '%{http_code}' http://localhost:3000)" -eq 200 ]; then
          echo "Website is accessible."
        else
          echo "Website is not accessible."
          exit 1
        fi

    - name: Stop Docker Container
      run: docker stop $(docker ps -q)
