name: unit-test

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - feature-*

jobs: 
  chai-unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name : Use Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test