name: unit-test

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - feature-*

jobs:
  chai-unit-testing:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: coffee-project
        run: npm install

      - name: Run unit tests
        working-directory: coffee-project
        run: npm run test

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4